name: Lapor Bug
description: Gunakan ini kalau nemu bug
title: "[BUG] Judul singkat bug-nya"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Makasih udah bantu laporan bug!

  - type: input
    id: what-happened
    attributes:
      label: Apa yang terjadi?
      placeholder: Jelasin bug-nya...
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Harusnya gimana?
      placeholder: Jelasin perilaku yang lo harapin
    validations:
      required: true