blank_issues_enabled: false
issue_templates:
  - name: Report a bug
    description: You can use this template if you find a bug.
    file: bug_report.yml
    
  - name: Request a feature
    description: Request new features or improvement ideas.
    file: feature_request.yml