blank_issues_enabled: false
contact_links:
  - name: Tanya di Discord
    url: https://discord.gg/link
    about: Kalau bingung atau butuh bantuan, bisa tanya di Discord.

issue_templates:
  - name: Report a bug
    description: You can use this template if you find a bug.
    file: bug_report.md